### PR TITLE
Replacing WebKit only Method Overload

### PR DESCRIPTION
**Pull request by bartimaeusnek**
This was done due to errors with Chromium-based Browsers

### CODE REVIEW

**Comment by HimbeersaftLP** [comment]
Hello, sorry for the late response. Can you tell me how to reproduce the bug that this fixes?
Also it would be helpful to have this in the .sh version as well, however I can also do that myself if you want.

**Comment by HimbeersaftLP** [comment]
@bartimaeusnek Sorry for the ping, but would you mind reading my reply above

**Comment by bartimaeusnek** [comment]
> Can you tell me how to reproduce the bug that this fixes?

I've the encountered the consistent behavior with the new edge (chromium based) that without this patch, the debugger tools just don't open at all but only show an error page.

No idea what else to say there...

**Comment by HimbeersaftLP** [comment]
I tried using the method scrollIntoViewIfNeeded with the bool parameter on Edge and it works fine for me, so I will close this PR If you still have the bug please tell me and I will add a fix,

**Pull request closed without merging**
